FROM rust:bullseye as builder
WORKDIR /usr/src/bbox
COPY . .
RUN cd bbox-server && cargo install --no-default-features --features=map-server --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y ca-certificates gnupg2 libcurl4 && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 46B5721DBBD2996A && \
    echo "deb https://qgis.org/debian bullseye main" > /etc/apt/sources.list.d/qgis.org.list && \
    apt-get update && apt-get install -y qgis-server-wms && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/bbox-server /usr/local/bin/bbox-server

USER www-data
WORKDIR /var/www

COPY bbox-map-server/qgis/plugins ./bbox-map-server/qgis/plugins

ENV BBOX_WEBSERVER__SERVER_ADDR=0.0.0.0:8080
#ENV BBOX_WMSSERVER__PATH=
#ENV BBOX_WMSSERVER__QGIS_BACKEND__PROJECT_BASEDIR=/data
ENV BBOX_METRICS__PROMETHEUS='{path="/metrics"}'
# ENV BBOX_FILESERVER__STATIC='[{dir="/static",path="static"}]'
# ENV BBOX_FILESERVER__REPO='[{dir="/plugins",path="qgis"}]'

CMD ["bbox-server"]
