FROM rust:bullseye as builder
WORKDIR /usr/src/bbox
COPY . .
RUN cd bbox-server && cargo install --no-default-features --features=map-server --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libcurl4 cgi-mapserver && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/bbox-server /usr/local/bin/bbox-server

USER www-data
WORKDIR /var/www

COPY --from=builder /usr/src/bbox/bbox-map-server.toml ./bbox.toml
COPY bbox-map-server/qgis/plugins ./bbox-map-server/qgis/plugins
CMD ["bbox-server"]
