FROM rust:bullseye as builder
WORKDIR /usr/src/bbox
COPY . .
RUN cd bbox-server && cargo install --no-default-features --features=map-server --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libcurl4 cgi-mapserver && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/bbox-server /usr/local/bin/bbox-server

WORKDIR /var/www
USER www-data
ENV BBOX_WEBSERVER__SERVER_ADDR="0.0.0.0:8080"
EXPOSE 8080
CMD ["bbox-server"]
