{
 "title": "bbox Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requests/h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(wmsapi_http_requests_total[60m])*3600",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wmsapi_http_requests_duration_seconds_sum[5m])/rate(wmsapi_http_requests_duration_seconds_count[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests/h Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(wmsapi_http_requests_total[5m])\n)*3600"
    }
   ]
  },
  {
   "title": "Request duration 90th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(wmsapi_http_requests_duration_seconds_bucket[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}