/*
 * A sample API conforming to the draft standard OGC API - Features - Part 1: Core
 *
 * This is a sample OpenAPI definition that conforms to the conformance classes \"Core\", \"GeoJSON\", \"HTML\" and \"OpenAPI 3.0\" of the draft standard \"OGC API - Features - Part 1: Core\".  This example is a generic OGC API Features definition that uses path parameters to describe all feature collections and all features. The generic OpenAPI definition does not provide any details on the collections or the feature content. This information is only available from accessing the feature collection resources.  There is [another example](ogcapi-features-1-example2.yaml) that specifies each collection explicitly.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@example.org
 * Generated by: https://openapi-generator.tech
 */

/// ExtentTemporal : The temporal extent of the features in the collection.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtentTemporal {
    /// One or more time intervals that describe the temporal extent of the dataset. The value `null` is supported and indicates an open time intervall. In the Core only a single time interval is supported. Extensions may support multiple intervals. If multiple intervals are provided, the union of the intervals describes the temporal extent.
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<Vec<Vec<String>>>,
    /// Coordinate reference system of the coordinates in the temporal extent (property `interval`). The default reference system is the Gregorian calendar. In the Core this is the only supported temporal reference system. Extensions may support additional temporal reference systems and add additional enum values.
    #[serde(rename = "trs", skip_serializing_if = "Option::is_none")]
    pub trs: Option<Trs>,
}

impl ExtentTemporal {
    /// The temporal extent of the features in the collection.
    pub fn new() -> ExtentTemporal {
        ExtentTemporal {
            interval: None,
            trs: None,
        }
    }
}

/// Coordinate reference system of the coordinates in the temporal extent (property `interval`). The default reference system is the Gregorian calendar. In the Core this is the only supported temporal reference system. Extensions may support additional temporal reference systems and add additional enum values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Trs {
    #[serde(rename = "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian")]
    HttpWwwOpengisNetDefUomISO86010Gregorian,
}

