/*
 * A sample API conforming to the draft standard OGC API - Features - Part 1: Core
 *
 * This is a sample OpenAPI definition that conforms to the conformance classes \"Core\", \"GeoJSON\", \"HTML\" and \"OpenAPI 3.0\" of the draft standard \"OGC API - Features - Part 1: Core\".  This example is a generic OGC API Features definition that uses path parameters to describe all feature collections and all features. The generic OpenAPI definition does not provide any details on the collections or the feature content. This information is only available from accessing the feature collection resources.  There is [another example](ogcapi-features-1-example2.yaml) that specifies each collection explicitly.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@example.org
 * Generated by: https://openapi-generator.tech
 */

/// ExtentSpatial : The spatial extent of the features in the collection.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtentSpatial {
    /// One or more bounding boxes that describe the spatial extent of the dataset. In the Core only a single bounding box is supported. Extensions may support additional areas. If multiple areas are provided, the union of the bounding boxes describes the spatial extent.
    #[serde(rename = "bbox", skip_serializing_if = "Option::is_none")]
    pub bbox: Option<Vec<Vec<f32>>>,
    /// Coordinate reference system of the coordinates in the spatial extent (property `bbox`). The default reference system is WGS 84 longitude/latitude. In the Core this is the only supported coordinate reference system. Extensions may support additional coordinate reference systems and add additional enum values.
    #[serde(rename = "crs", skip_serializing_if = "Option::is_none")]
    pub crs: Option<Crs>,
}

impl ExtentSpatial {
    /// The spatial extent of the features in the collection.
    pub fn new() -> ExtentSpatial {
        ExtentSpatial {
            bbox: None,
            crs: None,
        }
    }
}

/// Coordinate reference system of the coordinates in the spatial extent (property `bbox`). The default reference system is WGS 84 longitude/latitude. In the Core this is the only supported coordinate reference system. Extensions may support additional coordinate reference systems and add additional enum values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Crs {
    #[serde(rename = "http://www.opengis.net/def/crs/OGC/1.3/CRS84")]
    HttpWwwOpengisNetDefCrsOGC13CRS84,
}

