FROM rust:bookworm as builder
WORKDIR /usr/src/bbox
COPY . .
ARG BUILD_DIR=bbox-server
ARG BUILD_FEATURES=""

RUN cd $BUILD_DIR && cargo install $BUILD_FEATURES --path .

# ------
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y libcurl4 cgi-mapserver procps && \
    rm -rf /var/lib/apt/lists/*

ARG BUILD_DIR=bbox-server
ARG BUILDAPP=$BUILD_DIR

COPY --from=builder /usr/local/cargo/bin/$BUILDAPP /usr/local/bin/$BUILDAPP
RUN ln -s $BUILDAPP /usr/local/bin/bbox-app

WORKDIR /var/www
USER www-data
ENV BBOX_WEBSERVER__SERVER_ADDR="0.0.0.0:8080"
EXPOSE 8080
CMD ["bbox-app", "serve"]
