FROM rust:bookworm as builder
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/bbox
COPY . .
ARG BUILD_DIR=bbox-server
ARG BUILD_FEATURES=""

RUN cd $BUILD_DIR && cargo install $BUILD_FEATURES --path . --verbose

# ------
FROM debian:bookworm-slim

ARG DEBIAN_REPO=debian
RUN apt-get update && \
    apt-get install --no-install-recommends -y ca-certificates gnupg2 curl apt-utils && \
    curl -L https://qgis.org/downloads/qgis-2022.gpg.key | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import && \
    chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg && \
    echo "deb https://qgis.org/$DEBIAN_REPO bookworm main" > /etc/apt/sources.list.d/qgis.org.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y qgis-server-wms qgis-server-wfs && \
    rm -rf /var/lib/apt/lists/*

# Workaround for broken Proj data (last tested with proj-data 6.3.1-1)
RUN ln -s CHENYX06.gsb /usr/share/proj/CHENyx06a.gsb

ARG BUILD_DIR=bbox-server
ARG BUILDAPP=$BUILD_DIR

COPY --from=builder /usr/local/cargo/bin/$BUILDAPP /usr/local/bin/$BUILDAPP
RUN ln -s $BUILDAPP /usr/local/bin/bbox-app

COPY bbox-map-server/qgis/plugins /var/www/bbox-map-server/qgis/plugins

RUN chown -R www-data /var/www
WORKDIR /var/www
USER www-data
ENV BBOX_WEBSERVER__SERVER_ADDR="0.0.0.0:8080"
EXPOSE 8080
CMD ["bbox-app", "serve"]
